== Bootiful Vue Demo Steps

The brackets at the end of each step indicate the alias's or IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

=== Spring Boot API

. https://start.spring.io[start.spring.io]: h2, lombok, jpa, rest, web, and okta [`bootiful-start`]

  http https://start.spring.io/starter.zip dependencies==h2,lombok,data-jpa,data-rest,web,okta \
    packageName==com.okta.developer.demo -d

. Comment out Okta starter in `pom.xml`

. Add `Beer`, `BeerRepository`, `BeerCommandLineRunner` and add default beers [`boot-entity-lombok`, `boot-repo`, `boot-command`, `boot-add`]

. Start and see list of beers in console

. Create `BeerController` with a `/good-beers` endpoint [`boot-controller`, `boot-good`]

. Restart and confirm http://localhost:8080/good-beers works in browser and with http

  http POST :8080/beers name='Guinness'
  http PUT :8080/beers/1 name='Guinness is good for you'
  http DELETE :8080/beers/1

=== Vue App

. Run `vue create client`; choose **TypeScript**, **PWA**, and **Router**; show app with `npm start`

. Install axios: `npm i axios`

. Modify `Home.vue` and add a `created()` method to fetch good beers [`vue-created`]

. Create `Beer` interface and local `private beers: Beer[] = [];` variable

. Add beer list to `Home.vue` [`vue-list`]

  <h1>Beer List</h1>
  <div v-for="beer in beers">
    {{ beer.name }}
  </div>

. Create `client/vue.config.js` to proxy `/good-beers` requests [`vue-proxy`]

  module.exports = {
   devServer: {
     port: 8081,
     proxy: {
       "/good-beers": {
         target: "http://localhost:8080",
         secure: false
       }
     }
   }
  };

. Show beer list renders in browser

. Create `src/components/BeerList.vue` and copy code from `Home.vue`; change `Home.vue` to use `<BeerList/>`

. Create `GiphyImage.vue`; add to `BeerList`; show beers with images [`vue-giphy`]

. Use CSS Grid to layout images in rows [`vue-grid`]

=== PWA Support

. Run `npm run build`; serve with `serve -s dist -p 8081`

. Change URL to API in `BeerList.vue` and configure CORS for Spring Boot

. Restart, rebuild, and run Lighthouse

. Show how app works offline

. Mention Cloud Foundry and Heroku scripts

=== Authentication with Okta

. Uncomment Okta Spring Boot starter in `pom.xml`

. Create OIDC app in Okta; add properties to `application.properties` [`okta-oauth2`]

. Create Security configuration for resource server [`oauth2-resource-server`]

  @Configuration
  static class OktaOAuth2WebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
      @Override
      protected void configure(HttpSecurity http) throws Exception {
          http
              .authorizeRequests().anyRequest().authenticated()
              .and()
              .oauth2ResourceServer().jwt();
      }
  }

. Show access denied from http://localhost:8080 (known issue: https://github.com/okta/okta-spring-boot/issues/119[#119])

. Add Okta's Vue SDK and configure

  npm install -g @angular-devkit/schematics-cli
  npm i -D @oktadev/schematics
  schematics @oktadev/schematics:add-auth

. Show `router.ts` and how it uses `OktaVuePlugin` component; show auth awareness in `App.vue`

. Remove `<BeerList/>` from `Home.vue`; add `/beer-list` to routes in `router.ts` [`vue-route`]

. Add a link to `BeerList` in `App.vue` [`vue-link`]

. Restart client, navigate to **Good Beers**, see title only

. Update `BeerList` to add an authorization header [`vue-token`]

. Fix CORS error after adding Spring Security [`cors-filter`]

. Fini!

Source: https://developer.okta.com/blog/2018/12/03/bootiful-spring-boot-java-vue-typescript
